name: mobile_flutter
description: Field Sales Force Automation app (Flutter).
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.6.0
  isar: ^3.1.0
  drift: ^2.14.0
dev_dependencies:
  flutter_test:
    sdk: flutter
